export const LOG_OUT = "LOG_OUT";
export const LOG_OUT_ERR = "LOG_OUT_ERR";
export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const ADD_CUSTOMER_ERR = "ADD_CUSTOMER_ERR";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const DELETE_CUSTOMER_ERR = "DELETE_CUSTOMER_ERR";

